name: Build all Erlang versions and upload to PackageCloud

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * 1-5' # 08:30 mon-fri

jobs:
  build-all-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: depot/use-action@v1
        with:
          project: srqn8st7l7
      - name: Build all missing versions of Erlang and upload to PackageCloud
        env:
          GITHUB_TOKEN_PUBLIC_ACCESS: ${{ secrets.GITHUB_TOKEN }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run : bin/build-all-and-upload
