name: Build all Erlang versions and upload to PackageCloud

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * 1-5' # 08:30 mon-fri
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        image:
          - "ubuntu:noble"
        version:
          - "18.0"
          - "18.1"
          - "18.2"
          - "18.3"
          - "19.3.6.13"
          - "20.0.5"
          - "20.1.7.1"
          - "20.3.8.22"
          - "20.3.8.26"
        platform: [amd64, arm64]
      fail-fast: true
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - uses: depot/use-action@v1
      - name: Build Erlang version and upload to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run : bin/build-and-upload ${{ matrix.version }} ${{ matrix.image }} ${{ matrix.platform }}
