name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
          - 25.1
          - 24.3.3
          - 24.2.1
          - 24.2
          - 24.1.7
          - 24.0.4
          - 24.0.2
          - 24.0.1
          - 24.0
          - 23.2.3
          - 23.2.1
          - 23.2
          - 23.1.2
          - 23.0.3
          - 23.0.2
          - 22.3.4.9
          - 22.3.4.6
          - 22.3.4.3
          - 22.3.4.2
          - 21.3.8.16
          - 20.3.8.26
        include:
          #- image: ubuntu
          #  codename: jammy
          - image: ubuntu
            codename: focal
          - image: ubuntu
            codename: bionic
          - image: debian
            codename: bullseye
          #- image: debian
          #  codename: buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Export packages
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.image }}-${{ matrix.codename }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-${{ matrix.image }}-${{ matrix.codename }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            erlang_version=${{ matrix.erlang_version }}
            image=${{ matrix.image }}:${{ matrix.codename }}
            pkg_revision=${{ github.run_number }}
          outputs: pkgs
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: erlang-${{ matrix.image }}-${{ matrix.codename }}-pkgs
          path: pkgs
      - name: Upload to Packagecloud
        run: |
          set -euxo pipefail
          cat > $HOME/.curlrc << EOF
          -u "${{ secrets.packagecloud_token }}:"
          --no-progress-meter
          --fail
          EOF
          curl -O https://packagecloud.io/api/v1/distributions.json
          DIST_ID=$(jq ".deb[] | select(.index_name == \"${{ matrix.image }}\").versions[] | select(.index_name == \"${{ matrix.codename }}\").id" distributions.json)
          find pkgs -name "*.deb" | xargs -I@ basename @ | xargs -I@ curl -XDELETE "https://packagecloud.io/api/v1/repos/cloudamqp/erlang/${{ matrix.image }}/${{ matrix.codename }}/@" || true
          find pkgs -name "*.deb" | xargs -I{} curl -XPOST -F "package[distro_version_id]=$DIST_ID" -F "package[package_file]=@{}" https://packagecloud.io/api/v1/repos/cloudamqp/erlang/packages.json
        if: ${{ github.ref == 'refs/heads/main' }}
